AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Description: Domain name to host
  HostedZoneId:
    Type: String
    Description: "The Route53 hosted zone ID used for the domain"
  AcmCertificateArn:
    Type: String
    Description: "ACM Certificate ARN for hosted zone domain"
  PipelineExecutionRole:
    Type: String
    Description: "Pipeline execution role ARN"

Resources:
  HostingService:
    Type: AWS::Serverless::Application
    Properties:
      Location: hosting-service/template.yaml
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        AcmCertificateArn: !Ref AcmCertificateArn
        PipelineExecutionRole: !Ref PipelineExecutionRole


Outputs:
  BucketName:
    Description: "Bucket name"
    Value: !GetAtt HostingService.Outputs.BucketName
  DistributionId:
    Description: "CloudFront Distribution Id"
    Value: !GetAtt HostingService.Outputs.DistributionId
  DistributionURL:
    Description: "Distribution URL"
    Value: !Sub
    - https://${domain}/
    - domain: !GetAtt HostingService.Outputs.DistributionURL
